MTES-MCT/camino-api

- tasks/_utils/titre-prop-etape-id-find.js
Ajoute les points, substances, titulaires, etc., pour les formulations des demandes initiales.
> feat(tasks): prends en compte les étapes 'mfr' pour les demandes initiales

- src/tasks/daily/titres-phases-update.js
- src/tasks/etape-update/__mocks__/titre-demarche-statut-id-update-demarches.js
- src/tasks/etape-update/__mocks__/titre-demarches-ordre-update-demarches.js
- src/tasks/etape-update/__mocks__/titre-etape-communes-update-etapes.js
- src/tasks/etape-update/__mocks__/titre-etapes-ordre-update-demarches.js
- src/tasks/etape-update/__mocks__/titre-phases-update-titres.js
- src/tasks/etape-update/__mocks__/titre-props-etape-id-update-titres.js
- src/tasks/etape-update/__mocks__/titre-statut-id-update-titres.js
- src/tasks/etape-update/titre-demarche-statut-id-update.js
- src/tasks/etape-update/titre-demarche-statut-id-update.test.js
- src/tasks/etape-update/titre-demarches-ordre-update.test.js
- src/tasks/etape-update/titre-etape-communes-update.js
- src/tasks/etape-update/titre-etape-communes-update.test.js
- src/tasks/etape-update/titre-etapes-ordre-update.js
- src/tasks/etape-update/titre-etapes-ordre-update.test.js
- src/tasks/etape-update/titre-phases-update.js
- src/tasks/etape-update/titre-phases-update.test.js
- src/tasks/etape-update/titre-props-etape-id-update.js
- src/tasks/etape-update/titre-props-etape-id-update.test.js
- src/tasks/etape-update/titre-statut-id-update.test.js
- src/tasks/titre-etapes.js
- src/tasks/titre-phases.js
Dépend de https://github.com/MTES-MCT/camino-api/pull/14
> Ajoute les tests de src/tasks/etape-update

- src/tasks/rules/titre-demarche-phases-filter.test.js
fix (tasks) : corrections et reformulations de noms de tests
> [WIP] Corrections et reformulations de noms de tests

- src/api/resolvers/titres.js
corrige l'absence de 404 sur le front
> fix(api): retourne null si on appelle un titre dont l'id n'existe pas

- src/database/queries/titres.js
cherche aussi dans les noms et id.
> fix: corrige une requête sur les titres avec le filtre entreprises

- package-lock.json
- package.json
- src/database/queries/_format.js
- src/index.ts
https://github.com/getsentry/sentry-javascript/issues/2002
> fix (sentry): met à jour et corrige le bug sentry

- src/tasks/rules/__mocks__/titre-demarche-statut-id-find-demarches.js
- src/tasks/rules/titre-demarche-statut-id-find.js
- src/tasks/rules/titre-demarche-statut-id-find.test.js
> fix(tasks): corrige les statuts des démarches en fonction des étapes décisives

- knex/migrations/20180522000002_titres_demarches_etapes.js
- knex/migrations/20180522000003_titres_etapes_substances_emprises.js
- knex/migrations/20180522000004_titres_etapes_utilisateurs_titulaires_amodiataires_administrations.js
- knex/migrations/20180522000005_titres_etapes_points.js
- knex/migrations/20180522000006_titres_etapes_communes.js
- knex/migrations/20180522000007_titres_etapes_documents.js
- knex/migrations/20180522000008_titres_etapes_erreurs.js
- src/database/models/demarches-types.js
- src/database/models/titres-demarches.js
- src/database/models/titres-etapes.js
- src/database/queries/_options.js
- src/database/queries/titres-demarches.js
- src/database/queries/titres-etapes.js
- src/tasks/daily.ts
- src/tasks/processes/__mocks__/titre-demarche-id-update-demarches.js
- src/tasks/processes/administrations-update.js
- src/tasks/processes/titre-demarche-id-update.js
- src/tasks/processes/titre-demarche-id-update.test.js
- src/tasks/processes/titres-etapes-ordre-update.js
- src/tasks/processes/titres-etapes-ordre-update.test.js
- src/tasks/queries/titre-demarches.js
- src/tasks/titre-demarche-update.js
- src/tasks/titre-etape-update.js
- src/tasks/titre-etape-validation.js
- src/tasks/utils/__mocks__/titre-demarches-by-type-update-demarches.js
- src/tasks/utils/titre-demarches-by-type-update.js
- src/tasks/utils/titre-demarches-by-type-update.test.js
- src/tasks/utils/titre-etapes-by-type-update.js
- src/tools/dev/database/titres-demarches.js
https://trello.com/c/pWVdNRVF/275-featapi-ajout-et-modification-dune-d%C3%A9marche-changement-did
> feat(tasks): met à jour les identifiants de démarches

- src/api/resolvers/titres-demarches.js
- src/api/resolvers/titres-etapes.js
- src/database/queries/_options.js
- src/tasks/processes/__mocks__/titre-demarche-id-update-demarches.js
- src/tasks/processes/__mocks__/titre-etape-id-update-etapes.js
- src/tasks/processes/titre-demarches-id-update.test.js
- src/tasks/processes/titre-etape-id-update.js
- src/tasks/processes/titre-etape-id-update.test.js
- src/tasks/rules/titre-demarche-statut-id-find.js
- src/tasks/titre-demarche-update.js
- src/tasks/titre-etape-update.js
- src/tasks/utils/__mocks__/titre-demarches-asc-sort-demarches.js
- src/tasks/utils/element-relations-update.js
- src/tasks/utils/titre-demarches-asc-sort.js
- src/tasks/utils/titre-demarches-asc-sort.test.js
- src/tasks/utils/titre-demarches-by-type-update.js
- src/tasks/utils/titre-etapes-by-type-update.js
> fix(tasks): corrige la mise à jour des ids de démarches

- knex/seeds/4-repertoire.js
- knex/seeds/7-titres.js
- package-lock.json
- package.json
- src/tools/dev/json/load-sources.js
```sg
npx ts-node --transpile-only src/tools/dev/json/load-sources.js
```
> feat(tools): ajoute un script de vérification d'intégrité des données

- knex/seeding.js
- knex/seeds/1-metas.js
- knex/seeds/2-substances.js
- knex/seeds/3-territoires.js
- knex/seeds/4-repertoire.js
- knex/seeds/5-calendrier.js
- knex/seeds/6-utilisateurs.js
- knex/seeds/7-titres.js
- knex/seeds/8-metas-activites.js
- knex/seeds/9-titres-activites.js
Ceci est une proposition, discutons-en.
> fix(migrate): corrige la longueur des messages d'erreurs du seed lors de la migration

- src/business/rules/titre-prop-etape-id-find.js
Ex : https://camino.beta.gouv.fr/titres/w-prx-large-de-la-gironde-2011
> fix: corrige l'affichage des demandes classées sur la carte

- src/business/rules/__mocks__/titre-demarche-phases-filter-demarches.js
- src/business/rules/__mocks__/titre-demarche-statut-id-find-demarches.js
- src/business/rules/__mocks__/titre-phases-find-demarches.js
- src/business/rules/titre-date-debut-find.js
- src/business/rules/titre-demarche-date-fin-duree-find.js
- src/business/rules/titre-demarche-octroi-date-debut-find.js
- src/business/rules/titre-demarche-phases-filter.js
- src/business/rules/titre-demarche-phases-filter.test.js
- src/business/rules/titre-demarche-statut-id-find.js
- src/business/rules/titre-demarche-statut-id-find.test.js
- src/business/rules/titre-etape-publication-filter.js
- src/business/rules/titre-phases-find.js
- src/business/rules/titre-phases-find.test.js
- src/business/rules/titre-prop-etape-id-find.js
- Ajout de règles pour gérer les étapes `sco` des ARMs ;
- Factorisation du code dans une fonction `titreEtapePublicationFilter` ;
- Quelques retouches et ajouts de test pour les autres règles.
> feat : règles ARM et refactoring du dossier des règles métier

- src/database/queries/titres.js
Vérification basique pour ne pas écraser les titres.
À discuter.
> fix(business): n'écrase pas un titre existant si l'id du titre change

- src/tools/api-communes/index.js
- src/tools/api-insee/categories-juridiques.js
- src/tools/api-insee/index.js
> refactor(insee): améliore la gestion d'erreurs

- knex/seeds/3-territoires.js
- knex/seeds/5-calendrier.js
- knex/seeds/7-titres.js
- knex/seeds/8-metas-activites.js
- src/tools/dev/json/import-check.js
- src/tools/export/spreadsheets/titres.js
- src/tools/import/spreadsheets.js
Permet de gagner en performance pendant le daily.
> chore: exporte et importe les communes et les liens dans les titres

- src/business/titre-etape-updation-validate.js
- src/business/utils/titre-etape-numbers-check.js
> feat(édition): refuse les valeurs négatives sur les champs number

- src/business/definitions/titre-etapes-types-restrictions.js
> fix(api): corrige la validation des étapes de notifications au demandeur

- knex/migrations/20180522000006_titres_etapes_communes.js
- knex/migrations/20181106000002_titres_activites.js
- knex/migrations/20191209135237_titre_commune_surface.js
- knex/migrations/20191209203722_titre_commune_surface.js
- src/api/schemas/territoires.graphql
- src/api/schemas/titres.graphql
- src/business/daily.ts
- src/business/processes/titres-etapes-communes-update.js
- src/business/processes/titres-etapes-communes-update.test.js
- src/database/models/_format.js
- src/database/models/titres-communes.js
- src/database/models/titres-etapes.js
- src/database/models/titres.js
- src/database/queries/titres-etapes.js
- src/tools/api-communes/index.js
- src/tools/export/spreadsheets/titres.js
https://github.com/MTES-MCT/geo-communes-api/pull/8/files
> feat(communes): ajout de la surface couverte sur la commune par le titre

- src/tools/geo-convert.ts
- ajout de l'info ['EPSG:4624', '+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs '] dans proj4.defs du fichier geo-convert.ts
> fix(edition étape): Unexpected error value: "EPSG:4624"

- package.json
- src/tools/geo-convert.ts
alimente proj4 depuis les enregistrement de la table geo_systemes de la base
> Feat geosystem from database

- src/api/resolvers/format/entreprise.js
- src/api/resolvers/format/titre-activites.js
- src/api/resolvers/format/titre.js
- src/api/resolvers/format/utilisateur.js
- src/api/resolvers/graph/format.js
- src/api/resolvers/titres-activites.js
- src/api/resolvers/utilisateurs.js
- src/api/schemas/documents.graphql
- src/api/schemas/entreprises.graphql
- src/api/schemas/titres-activites.graphql
- src/api/schemas/utilisateurs.graphql
https://github.com/MTES-MCT/camino-ui/pull/67
> feat(api): supprime des vérifications de permissions du front

- knex/migrations/20181106000001_metas_activites.js
- src/business/daily.ts
- src/business/processes/__mocks__/titres-activites-statut-ids-update-activites.js
- src/business/processes/titres-activites-statut-ids-update.js
- src/business/processes/titres-activites-statut-ids-update.test.js
- src/business/rules/__mocks__/titre-activite-statut-id-find-activites.js
- src/business/rules/titre-activite-statut-id-find.js
- src/business/rules/titre-activite-statut-id-find.test.js
- src/database/models/activites-types.ts
- src/database/models/titres-activites.ts
Co-authored-by: Adrien Risser <risseraka@gmail.com>
> feat(activité) : fixe une date au delà de laquelle  un rapport passe au statut "fermé"

- src/database/queries/titres.ts
Enlève les guillemets pour une requête "Grand Est".
> fix(api): corrige la regex dans filtre de recherche

- dev/database/titres-arm-etapes-contenu-migrate.js
- dev/database/titres-arm-etapes-def-contenu-migrate.js
- dev/database/titres-arm-etapes-mcr-to-mcp-migrate.js
- dev/database/titres-contenu-migrate.js
- dev/database/titres-xxx-mdp-to-mfr-copy.js
- src/api/resolvers/titres-etapes.ts
Dépend de https://github.com/MTES-MCT/camino-api/pull/323
> feat(data): copie le dépôt de la demande vers une étape de demande si elle n'existe pas

- dev/database/titres-arm-etapes-contenu-migrate.js
- dev/database/titres-arm-etapes-def-contenu-migrate.js
- dev/database/titres-arm-etapes-mcr-to-mcp-migrate.js
- dev/database/titres-contenu-migrate.js
- dev/database/titres-xxx-dpu-dex-to-dup-dux.js
- dev/database/titres-xxx-mdp-to-mfr-copy.js
- src/api/resolvers/titres-etapes.ts
Dépend de https://github.com/MTES-MCT/camino-api/pull/327
> feat(data): migre les étapes dpu et dex vers les étapes unilatérales dup et dux respectives

- src/api/resolvers/titres-etapes.ts
- src/business/daily.ts
- src/business/definitions/titres-types-etapes-types-restrictions/arm.ts
- src/business/rules/titre-contenu-etape-id-find.ts
- src/business/rules/titre-prop-etape-id-find.ts
- src/business/titre-demarche-update.ts
- src/business/titre-etape-update.ts
- src/business/utils/titre-etape-date-validate.js
- src/business/utils/titre-etape-date-validate.test.js
- src/database/models/_format.ts
Dépend de https://github.com/MTES-MCT/camino-api/pull/324
> feat(etapes): limite la liste des étapes possibles pendant l'édition suivant les règles métiers

- src/database/queries/titres-demarches.ts
https://github.com/MTES-MCT/camino-ui/pull/106
> fix(demarches): corrige le tri des démarches

- src/api/graphql/resolvers/documents.ts
ajoute `entreprisesLecture` si `publicLecture` est `true`.
> fix(documents): ajuste les permissions

- src/database/queries/permissions/administrations.ts
- src/database/queries/permissions/entreprises.ts
- src/database/queries/permissions/titres-activites.ts
- src/database/queries/permissions/titres-demarches.ts
- src/database/queries/titres.ts
> fix(titres): corrige la requête sur les titres

- README.md
- src/api/graphql/resolvers/utilisateurs.ts
- src/business/utilisateur-updation-validate.ts
Co-authored-by: Adrien Risser <risseraka@gmail.com>
> fix(utilisateur): oblige un admin à être attaché à une administration

- knex/migrations/20181106000001_metas_activites.js
- src/database/models/activites-types.ts
- src/database/models/titres-activites.ts
- src/database/queries/metas.ts
Attendre la MEP pour modifier la spreadsheet
> feat(activites):  fixe un ordre de présentation des rapports PRM

- tests/_utils.ts
enlève les erreurs dans les logs qui les rendaient illisibles
> test(tests): vérifie l’existence de l’utilisateur avant de le créer

- tsconfig.json
dans Architecture et dans Deploiement
> docs(archi & deploy): complète la génération automatique de la doc

- dev/json/documents-migrate.js
- dev/json/titres-reprise.js
- src/business/processes/titres-etapes-areas-update.test.ts
- src/business/processes/titres-etapes-areas-update.ts
- src/business/rules/titre-activites-build.test.ts
- src/business/utils/activites-types-filter.test.ts
- src/database/queries/permissions/titres.ts
- src/database/queries/titres.ts
- tests/__mocks__/administrations.ts
- tests/_utils.ts
- tests/documents.test.ts
- tests/entreprises.test.ts
- tests/titres-demarches.test.ts
- tests/titres-etapes-creer.test.ts
- tests/titres-etapes-modifier.test.ts
- tests/titres.test.ts
- tests/utilisateurs.test.ts
Sur les titres non-publics, les administrations ne peuvent voir que les titres qui les concernent.
> feat: restreint l'accès des administrations aux titres non-publics

- src/api/graphql/resolvers/_titre-activite.ts
> feat(rapports): ajout des unités dans les rapports

- knex/migrations/20180521000002_demarches_etapes.js
- knex/migrations/20180521000009_repertoire.js
- sources/activites-types.json
- sources/administrations--activites-types.json
- sources/administrations.json
- sources/demarches-types.json
- sources/documents-types.json
- sources/etapes-statuts.json
- sources/etapes-types--etapes-statuts.json
- sources/etapes-types.json
- sources/references-types.json
- sources/substances.json
- sources/titres-types--demarches-types--etapes-types.json
- sources/titres-types.json
- sources/travaux-types.json
- src/api/graphql/resolvers/documents.ts
- src/api/graphql/schemas/metas.graphql
- src/api/rest/fichiers.ts
- src/database/models/documents-types.ts
- src/database/queries/metas.ts
- src/dev/database/documents-types-repertoire-delete.ts
- src/tools/documents/document-repertoire-find.ts
- src/tools/documents/documents-index-build.ts
- src/types.ts
- tests/titres-etapes-creer.test.ts
Co-authored-by: vmaubert <vmaubert@users.noreply.github.com>
> fix(documents): supprime la colonne répertoire

- .husky/pre-commit
- .husky/pre-push
- package-lock.json
- package.json
J'ai paramétré un `test` pré-push et un`lint` pré-commit. 
L'idée étant qu'une rapide correction du linter évite un commit dédié plus tard...
Dis-moi si tu trouves ça de trop.
> chore(git): ajout de husky

- package-lock.json
- package.json
- src/@types/tus-node-server.d.ts
- src/api/graphql/resolvers/documents.ts
- src/api/graphql/resolvers/utilisateurs.ts
- src/api/graphql/schemas/documents.graphql
- src/database/models/documents.ts
- src/index.ts
- src/server/upload.test.ts
- src/server/upload.ts
- src/types.ts
- tests/_utils/index.ts
- tests/app.ts
- tests/jest-setup.ts
- tests/setup.ts
- tests/upload.test.ts
- téléversement à pauses et reprises
- barre de progression dans l'UI
> feat(upload): renforce les capacités de téléversement

- src/api/graphql/resolvers/_titre-activite.ts
- src/api/graphql/resolvers/administrations.ts
- src/database/queries/administrations.ts
- src/database/queries/permissions/administrations-activites-types-emails.ts
- src/database/queries/permissions/administrations.test.ts
- un ajout remplaçait une entrée existante
- la requête retournait une nombre erroné d'entrées
> fix(activitesTypesEmail): corrige deux erreurs dans l'ajout et la requête d'email

- package.json
- src/api/graphql/resolvers/titres-etapes.ts
- src/business/processes/titres-demarches-depot-create.test.ts
- src/business/processes/titres-demarches-depot-create.ts
- src/business/titre-etape-update.ts
- src/database/user-super.ts
- src/knex/migrations-data/20211215100715_utilisateurs-camino-create.js
pour que l’administration puisse étudier sa recevabilité
> feat(axm): dépose automatiquement la demande d’ARM

- src/api/graphql/resolvers/utilisateurs.ts
- corrige un problème de navigation avec Safari
> fix(cookie): permet d'utiliser les cookies en local
